// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
#include "main.h"
#include <stdlib.h>

// Exported Functions from `twin:test/stateful`



__attribute__((__weak__, __export_name__("cabi_post_twin:test/stateful#[method]clip-projector.get-components")))
void __wasm_export_exports_twin_test_stateful_method_clip_projector_get_components_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      size_t len = *((size_t*) (arg0 + 8));
      if (len > 0) {
        uint8_t *ptr = *((uint8_t **) (arg0 + 4));
        for (size_t i = 0; i < len; i++) {
          uint8_t *base = ptr + i * 16;
          (void) base;
        }
        free(ptr);
      }
      break;
    }
    case 1: {
      break;
    }
  }
}




// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void twin_test_math_mat4_free(twin_test_math_mat4_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    float *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void exports_twin_test_stateful_mat4_free(exports_twin_test_stateful_mat4_t *ptr) {
  twin_test_math_mat4_free(ptr);
}

__attribute__((__import_module__("[export]twin:test/stateful"), __import_name__("[resource-drop]clip-projector")))
extern void __wasm_import_exports_twin_test_stateful_clip_projector_drop(int32_t handle);

void exports_twin_test_stateful_clip_projector_drop_own(exports_twin_test_stateful_own_clip_projector_t handle) {
  __wasm_import_exports_twin_test_stateful_clip_projector_drop(handle.__handle);
}

__attribute__(( __import_module__("[export]twin:test/stateful"), __import_name__("[resource-new]clip-projector")))
extern int32_t __wasm_import_exports_twin_test_stateful_clip_projector_new(int32_t);

__attribute__((__import_module__("[export]twin:test/stateful"), __import_name__("[resource-rep]clip-projector")))
extern int32_t __wasm_import_exports_twin_test_stateful_clip_projector_rep(int32_t);

exports_twin_test_stateful_own_clip_projector_t exports_twin_test_stateful_clip_projector_new(exports_twin_test_stateful_clip_projector_t *rep) {
  return (exports_twin_test_stateful_own_clip_projector_t) { __wasm_import_exports_twin_test_stateful_clip_projector_new((int32_t) rep) };
}

exports_twin_test_stateful_clip_projector_t* exports_twin_test_stateful_clip_projector_rep(exports_twin_test_stateful_own_clip_projector_t handle) {
  return (exports_twin_test_stateful_clip_projector_t*) __wasm_import_exports_twin_test_stateful_clip_projector_rep(handle.__handle);
}

__attribute__((__export_name__("twin:test/stateful#[dtor]clip_projector")))
void __wasm_export_exports_twin_test_stateful_clip_projector_dtor(exports_twin_test_stateful_clip_projector_t* arg) {
  exports_twin_test_stateful_clip_projector_destructor(arg);
}

void exports_twin_test_stateful_list_component_free(exports_twin_test_stateful_list_component_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_twin_test_stateful_component_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void exports_twin_test_stateful_result_list_component_void_free(exports_twin_test_stateful_result_list_component_void_t *ptr) {
  if (!ptr->is_err) {
    exports_twin_test_stateful_list_component_free(&ptr->val.ok);
  }
}

void exports_twin_test_stateful_result_void_void_free(exports_twin_test_stateful_result_void_void_t *ptr) {
  if (!ptr->is_err) {
  }
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[12];

__attribute__((__export_name__("twin:test/stateful#[constructor]clip-projector")))
int32_t __wasm_export_exports_twin_test_stateful_constructor_clip_projector(void) {
  exports_twin_test_stateful_own_clip_projector_t ret = exports_twin_test_stateful_constructor_clip_projector();
  return (ret).__handle;
}

__attribute__((__export_name__("twin:test/stateful#[method]clip-projector.get-components-count")))
int32_t __wasm_export_exports_twin_test_stateful_method_clip_projector_get_components_count(uint8_t * arg) {
  uint32_t ret = exports_twin_test_stateful_method_clip_projector_get_components_count(((exports_twin_test_stateful_clip_projector_t*) arg));
  return (int32_t) (ret);
}

__attribute__((__export_name__("twin:test/stateful#[method]clip-projector.get-components")))
uint8_t * __wasm_export_exports_twin_test_stateful_method_clip_projector_get_components(uint8_t * arg) {
  exports_twin_test_stateful_result_list_component_void_t ret;
  exports_twin_test_stateful_list_component_t ok;
  ret.is_err = !exports_twin_test_stateful_method_clip_projector_get_components(((exports_twin_test_stateful_clip_projector_t*) arg), &ok);
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    *((int8_t*)(ptr + 0)) = 1;
  } else {
    const exports_twin_test_stateful_list_component_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + 8)) = (*payload).len;
    *((uint8_t **)(ptr + 4)) = (uint8_t *) (*payload).ptr;
  }
  return ptr;
}

__attribute__((__export_name__("twin:test/stateful#[method]clip-projector.fill-components")))
int32_t __wasm_export_exports_twin_test_stateful_method_clip_projector_fill_components(uint8_t * arg, uint8_t * arg0, size_t arg1) {
  exports_twin_test_stateful_list_component_t arg2 = (exports_twin_test_stateful_list_component_t) { (exports_twin_test_stateful_component_t*)(arg0), (arg1) };
  exports_twin_test_stateful_result_void_void_t ret;
  ret.is_err = !exports_twin_test_stateful_method_clip_projector_fill_components(((exports_twin_test_stateful_clip_projector_t*) arg), &arg2);
  int32_t result;
  if ((ret).is_err) {
    result = 1;
  } else {
    result = 0;
  }
  return result;
}

__attribute__((__export_name__("twin:test/stateful#[method]clip-projector.set-projection")))
int32_t __wasm_export_exports_twin_test_stateful_method_clip_projector_set_projection(uint8_t * arg, uint8_t * arg0, size_t arg1) {
  exports_twin_test_stateful_mat4_t arg2 = (twin_test_math_mat4_t) { (float*)(arg0), (arg1) };
  exports_twin_test_stateful_result_void_void_t ret;
  ret.is_err = !exports_twin_test_stateful_method_clip_projector_set_projection(((exports_twin_test_stateful_clip_projector_t*) arg), &arg2);
  int32_t result;
  if ((ret).is_err) {
    result = 1;
  } else {
    result = 0;
  }
  return result;
}

__attribute__((__export_name__("twin:test/stateful#[method]clip-projector.project")))
void __wasm_export_exports_twin_test_stateful_method_clip_projector_project(uint8_t * arg) {
  exports_twin_test_stateful_method_clip_projector_project(((exports_twin_test_stateful_clip_projector_t*) arg));
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_main(void);
void __component_type_object_force_link_main_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_main();
}
